---
# Per environment values which override defaults in hmpps-contacts-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: contacts-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: 'https://contacts-dev.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in-dev.hmpps.service.justice.gov.uk/auth'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api-dev.prison.service.justice.gov.uk'
    COMPONENT_API_URL: 'https://frontend-components-dev.hmpps.service.justice.gov.uk' # used by hmpps-connect-dps-components module
    DPS_HOME_PAGE_URL: 'https://digital-dev.prison.service.justice.gov.uk'
    PRISONER_SEARCH_API_URL: 'https://prisoner-search-dev.prison.service.justice.gov.uk'
    PRISON_API_URL: 'https://prison-api-dev.prison.service.justice.gov.uk'
    CONTACTS_API_URL: 'https://personal-relationships-api-dev.hmpps.service.justice.gov.uk'
    ORGANISATIONS_API_URL: 'https://organisations-api-dev.hmpps.service.justice.gov.uk'
    ALERTS_API_URL: 'https://alerts-api-dev.hmpps.service.justice.gov.uk'
    PRISONER_PROFILE_PAGE_URL: 'https://prisoner-dev.digital.prison.service.justice.gov.uk'
    COMMON_COMPONENTS_ENABLED: true
    ENVIRONMENT_NAME: DEV
    SENTRY_ENVIRONMENT: DEV
    AUDIT_ENABLED: 'true'

  allowlist:
    groups:
      - prisons
      - moj_cloud_platform
      - digital_staff_and_mojo

generic-prometheus-alerts:
  alertSeverity: hmpps-contacts-ui-dev
  businessHoursOnly: true
